name: CI

on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script again
      run: echo Hello, world!
      
    - name: Run a multi-line script again
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
  
